/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_pascal_terminal_TerminalHandle */

#ifndef _Included_net_pascal_terminal_TerminalHandle
#define _Included_net_pascal_terminal_TerminalHandle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_pascal_terminal_TerminalHandle
 * Method:    getch
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_pascal_terminal_TerminalHandle_getch
  (JNIEnv *, jobject);

/*
 * Class:     net_pascal_terminal_TerminalHandle
 * Method:    getSize
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_net_pascal_terminal_TerminalHandle_getSize
  (JNIEnv *, jobject);

/*
 * Class:     net_pascal_terminal_TerminalHandle
 * Method:    resetInputBuffer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_pascal_terminal_TerminalHandle_resetInputBuffer
  (JNIEnv *, jobject);

/*
 * Class:     net_pascal_terminal_TerminalHandle
 * Method:    setTitle
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_pascal_terminal_TerminalHandle_setTitle
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_pascal_terminal_TerminalHandle
 * Method:    setCursorVisible
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_net_pascal_terminal_TerminalHandle_setCursorVisible
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
